# Generated by Django 4.2.6 on 2023-11-05 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout', models.CharField()),
                ('targetArea', models.TextField()),
                ('equipment', models.TextField()),
                ('bodypart', models.TextField()),
                ('instructions', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.person')),
            ],
        ),
    ]
