# Generated by Django 4.2.6 on 2023-11-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_workout_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout_plan',
            name='person',
        ),
    ]
