# Generated by Django 4.2.6 on 2023-11-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(default='bye', max_length=60, verbose_name='password'),
            preserve_default=False,
        ),
    ]
