from ninja import NinjaAPI
from ninja.response import codes_2xx
from .schema import WorkoutSchema , ErrorSchema
from django.shortcuts import get_object_or_404
from authentication.models import Person
from .models import Workout

api = NinjaAPI()

@api.get("/excersise/workout/{workout_id}", response={200: WorkoutSchema, 404: NotFoundSchema})
def getWorkouts(self, request, workout_id: int):
    try:
        workout = Workout.object.get(pk=workout_id)
        return 200, workout
    except:
        message = 'workout with that id not found'
        return 404, message

# Need endpoint to create workouts
@api.apioperation(["GET","POST"], "excersise/create_workouts/{person_id}", response={codes_2xx: WorkoutSchema, 500: ErrorSchema})
def makeWorkouts(request, person_id: int):
    person = Person.objects.filter(pk=person_id)
    person_obj = get_object_or_404(Person)


#Need endpoint display all workouts per user generated by the script




    
    