from ninja import NinjaAPI
from ninja.response import code_2xx
from .schema import WorkoutSchema
from .models import Workout

api = NinjaAPI()

@api.get("/workout/{workout_id}", response={200: WorkoutSchema, 404: NotFoundSchema})
def getWorkouts(self, request, workout_id: int):
    try:
        workout = Workout.object.get(pk=workout_id)
        return 200, workout
    except:
        message = 'workout with that id not found'
        return 404, message

# Need endpoint to create workouts
# @api.apioperation(["GET","POST"], "create_workouts/", response={202: WorkoutSchema})
# def makeWorkouts(self, request, person_id: int):


#Need endpoint display all workouts per user generated by the script




    
    